package pl.kiosel.villages.enums;

import lombok.Getter;

public enum Lang {

	COMMAND_RELOAD("command.reload"),
	COMMAND_CONSOLE("command.no-console"),
	COMMAND_ENABLED("command.not-enabled"),
	COMMAND_NO_PERMISSION("command.no-permission"),
	COMMAND_INVALID("command.invalid-number"),
	COMMAND_VILLAGE_NOT_FOUND("command.village-not-found"),
	COMMAND_UNKNOWN("command.unknown"),
	COMMAND_USAGE_CHAT("command.usage.chat"),
	COMMAND_USAGE_INVITE("command.usage.invite"),
	COMMAND_USAGE_REQUEST("command.usage.request"),
	COMMAND_USAGE_BUILD_EDITOR("command.usage.build-editor"),
	COMMAND_ADMIN_VILLAGE_BLOCK("command.admin.village-block"),
	COMMAND_ADMIN_DESTROYER("command.admin.destroyer"),
	COMMAND_ADMIN_UPGRADE("command.admin.upgrade"),
	COMMAND_ADMIN_CANT_UPGRADE("command.admin.cant-upgrade"),
	COMMAND_ADMIN_DELETE("command.admin.delete"),
	COMMAND_ADMIN_PROTECTION_ADD("command.admin.protection-add"),
	COMMAND_ADMIN_PROTECTION_REMOVE("command.admin.protection-remove"),

	COMMAND_ADMIN_BANK_ADD("command.admin.bank-add"),
	COMMAND_ADMIN_BANK_REMOVE("command.admin.bank-remove"),

	COMMAND_ADMIN_LIVES_ADD("command.admin.lives-add"),
	COMMAND_ADMIN_LIVES_REMOVE("command.admin.lives-remove"),
	COMMAND_ADMIN_ALREADY_DYING("command.admin.already-dying"),
	COMMAND_ADMIN_UPGRADE_FAILED("command.admin.upgrade-failed"),
	COMMAND_ADMIN_USAGE_ROOT("command.admin.usage.root"),
	COMMAND_ADMIN_USAGE_GIVE("command.admin.usage.give"),
	COMMAND_ADMIN_USAGE_MANAGE("command.admin.usage.manage"),
	COMMAND_ADMIN_USAGE_ACTION("command.admin.usage.action"),
	COMMAND_ADMIN_USAGE_NUMBER("command.admin.usage.number"),
	COMMAND_ADMIN_USAGE_DURATION("command.admin.usage.duration"),

	ADDON_DISABLED("general.addon-disabled"),
	FULL_EQ("general.player.you-have-full-eq"),
	MONEY_REMOVE("general.player.money-remove"),
	MONEY_ADD("general.player.money-add"),
	NO_MONEY("general.player.money-no"),
	NO_XP("general.player.no-xp"),
	NO_ITEMS("general.player.no-items"),
	MISSING_ITEM("general.player.missing-item"),
    PLAYER_OFFLINE("general.player.offline"),
	PLAYER_ONLINE("general.player.online"),
	PLAYER_NOT_FOUND("general.player.not-found"),
    HAS_VILLAGE("general.player.has-village"),
	TAKE_XP("general.player.take-xp"),
	TAKE_ITEMS("general.player.take-items"),
	SEPARATOR("general.separator"),
	NEXT("general.nametag.next"),
	BACK("general.nametag.back"),
	EXIT("general.nametag.exit"),
	BLANK("general.nametag.blank"),
	PREVIOUS("general.nametag.previous"),
	ON("general.nametag.on"),
	OFF("general.nametag.off"),
	YES("general.nametag.yes"),
	NO("general.nametag.no"),

	TELEPORT("teleport.teleporting"),
	TELEPORTED("teleport.teleported"),
	TELEPORT_COOLDOWN("teleport.cooldown"),
	TELEPORT_TITLE("teleport.title"),
	TELEPORT_SUBTITLE("teleport.subtitle"),
	TELEPORT_MOVE("teleport.move"),
	TELEPORT_SET("teleport.set"),
	TELEPORT_SET_CANCEL("teleport.set-cancel"),
	TELEPORT_SET_HOVER("teleport.set-hover"),
	TELEPORT_SET_TITLE("teleport.set-title"),
	TELEPORT_SET_SUBTITLE("teleport.set-subtitle"),
	TELEPORT_SET_OUT_OF_VILLAGE("teleport.outside-region"),

	CREATED("village.created"),
	DISABLED_WORLD("village.disabled-world"),
	VILLAGE_NO_PERMISSION("village.no-permission"),
	VILLAGE_NEARBY("village.nearby"),
	VILLAGE_SPAWN("village.spawn-nearby"),
	VILLAGE_REMOVE("village.remove"),
	VILLAGE_REMOVE_MEMBER("village.remove-member"),
	VILLAGE_UPGRADE("village.upgrade"),
	VILLAGE_CHAT_FORMAT("village.chat-format"),
	VILLAGE_NO_REQ_UPGRADE("village.upgrade-no-requirements"),
	VILLAGE_MAX_LEVEL("village.max-level"),
	VILLAGE_PROTECTED("village.protected"),
	VILLAGE_PROTECTED_OFFLINE("village.protected-offline-members"),
	VILLAGE_MUST_HAVE_TAG("village.have-tag"),
	VILLAGE_ATTACKED_TITLE("village.attacked.title"),
	VILLAGE_ATTACKED_SUBTITLE("village.attacked.subtitle"),
	VILLAGE_ATTACKED_MESSAGE("village.attacked.message"),
	VILLAGE_DESTROYED_TITLE("village.destroyed.title"),
	VILLAGE_DESTROYED_SUBTITLE("village.destroyed.subtitle"),
	VILLAGE_DESTROYED_MESSAGE("village.destroyed.message"),

	VILLAGE_IN("village.in-village"),
    VILLAGE_NO("village.no-village"),
    LEAVE_OWNER("village.leave-owner"),
	LEAVE_VILLAGE("village.leave-village"),
	LEAVE_VILLAGE_BROADCAST("village.leave-village-broadcast"),
	LEAVE_CONFIRM_VILLAGE("village.confirm-leave-village"),
	CANT_EDIT("village.cant-edit"),
	EFFECT_NOT_BUY("village.effect-not-bought"),

	BANK_ADD("village.bank-add"),
	BANK_REMOVE("village.bank-remove"),
	BANK_NO_MONEY("village.bank-no-money"),

	ENTER_VILLAGE_AREA_TITLE("village.enter-area-title"),
	ENTER_VILLAGE_AREA_SUBTITLE("village.enter-area-subtitle"),
	LEAVE_VILLAGE_AREA_TITLE("village.leave-area-title"),
	LEAVE_VILLAGE_AREA_SUBTITLE("village.leave-area-subtitle"),

	ANVIL_NAME("tag.anvil-name-your-village"),
	TAG_VILLAGE("tag.your-village-tag"),
	TAG_NEW_VILLAGE("tag.new-village-tag"),
	TAG_NO_SET_VILLAGE("tag.closed-name-village-tag"),
	TAG_ALREADY_SET_VILLAGE("tag.already-name-village-tag"),
	TAG_TRY_AGAIN("tag.try-again"),
	TAG_SPACES("tag.has-spaces"),
	TAG_TOO_LONG("tag.too-long"),
	TAG_INVALID_CHARS("tag.invalid-chars"),
	TAG_NO("tag.no-tag"),

    HAS_INVITE("invite.has-invite"),
	NO_INVITE("invite.no-invite"),
	MAX_MEMBERS("invite.max-members"),
    PLAYER_INVITE("invite.player-invite"),
    PLAYER_TARGET("invite.player-target"),
	INVITE_CONFIRM("invite.confirm"),
	INVITE_CANCEL("invite.cancel"),
	INVITE_CONFIRM_HOVER("invite.confirm-hover-click"),
	INVITE_CANCEL_HOVER("invite.cancel-hover-click"),
	INVITE_CONFIRMED("invite.confirmed"),
	INVITE_DECLINE("invite.target-decline-member"),
	INVITE_CANCELED("invite.canceled"),
	TARGET_JOIN_MEMBER("invite.target-join-member"),

	SPAWN_SET("spawn.spawn-set"),
	SPAWN_NOT_SET("spawn.spawn-not-set"),
	SPAWN_TELEPORT("spawn.teleporting"),

	ANTILOGOUT_BLOCKED_REGION("antilogout.blocked-region"),
	ANTILOGOUT_BLOCK_COMMAND("antilogout.block-command"),
	ANTILOGOUT_STARTED("antilogout.started"),
	ANTILOGOUT_ATTACKED("antilogout.attacked"),
	ANTILOGOUT_END_COMBAT("antilogout.end-combat"),
	ANTILOGOUT_REMOVE_COMBAT("antilogout.remove-combat"),
	ANTILOGOUT_ACTIONBAR_MESSAGE("antilogout.actionbar-message"),
	ANTILOGOUT_QUIT_BROADCAST("antilogout.quit-broadcast"),

	QUESTS_COMMAND_DESCRIPTION("quests.command-description"),
	QUESTS_COMPLETED("quests.completed"),
	QUESTS_ACTIVATED("quests.activated"),
	QUESTS_GUI_MENU_NAME("quests.gui.menu-name"),
	QUESTS_GUI_MENU_LORE("quests.gui.menu-lore"),
	QUESTS_GUI_DAILY("quests.gui.daily"),
	QUESTS_GUI_WEEKLY("quests.gui.weekly"),
	QUESTS_GUI_PROGRESS("quests.gui.progress"),
	QUESTS_GUI_COMPLETED("quests.gui.completed"),
	QUESTS_GUI_ACTIVE("quests.gui.active"),
	QUESTS_GUI_INACTIVE("quests.gui.inactive"),
	QUESTS_GUI_ACTIVATE("quests.gui.activate"),
	QUESTS_GUI_RESET("quests.gui.reset"),
	QUESTS_GUI_REWARDS("quests.gui.rewards"),
	QUESTS_GUI_REWARD_BANK("quests.gui.reward-bank"),
	QUESTS_GUI_REWARD_EXPERIENCE("quests.gui.reward-experience"),
	QUESTS_GUI_REWARD_POINTS("quests.gui.reward-points"),
	QUESTS_GUI_NONE("quests.gui.none"),

	LOGS_GUI_MENU_NAME("logs.gui.menu-name"),
	LOGS_GUI_MENU_LORE("logs.gui.menu-lore"),
	LOGS_GUI_NONE("logs.gui.none"),
	LOGS_GUI_ACTOR("logs.gui.actor"),
	LOGS_GUI_DATE("logs.gui.date"),
	LOGS_GUI_GROUPED("logs.gui.grouped"),
	LOGS_SYSTEM("logs.system"),

	RANKING_KILL("ranking.kill"),
	RANKING_DEATH("ranking.death"),
	RANKING_ASSIST("ranking.assist"),

	BUILD_EDITOR_WORLD_EDIT_REQUIRED("build-editor.worldedit-required"),
	BUILD_EDITOR_SETTING_REQUIRED("build-editor.setting-required"),
	BUILD_EDITOR_SESSION_ACTIVE("build-editor.session-active"),
	BUILD_EDITOR_LEVEL_MISSING("build-editor.level-missing"),
	BUILD_EDITOR_SCHEMATIC_MISSING("build-editor.schematic-missing"),
	BUILD_EDITOR_SCHEMATIC_TOO_LARGE("build-editor.schematic-too-large"),
	BUILD_EDITOR_SAFE_LOCATION_NOT_FOUND("build-editor.safe-location-not-found"),
	BUILD_EDITOR_STARTED("build-editor.started"),
	BUILD_EDITOR_BOUNDS_HELP("build-editor.bounds-help"),
	BUILD_EDITOR_COMMANDS_HELP("build-editor.commands-help"),
	BUILD_EDITOR_LOAD_FAILED("build-editor.load-failed"),
	BUILD_EDITOR_NO_SESSION("build-editor.no-session"),
	BUILD_EDITOR_SAVED("build-editor.saved"),
	BUILD_EDITOR_SAVED_HELP("build-editor.saved-help"),
	BUILD_EDITOR_SAVE_FAILED("build-editor.save-failed"),
	BUILD_EDITOR_CANCELED("build-editor.canceled"),
	BUILD_EDITOR_CORE_PROTECTED("build-editor.core-protected"),
	BUILD_EDITOR_OUTSIDE_BOUNDS("build-editor.outside-bounds"),
	BUILD_EDITOR_AREA_IN_USE("build-editor.area-in-use"),
	BUILD_EDITOR_SETUP_ACTIVE("build-editor.setup-active"),
	BUILD_EDITOR_MAX_LEVEL("build-editor.max-level"),
	BUILD_EDITOR_SETUP_RESUMED("build-editor.setup-resumed"),
	BUILD_EDITOR_NEW_LEVEL_STARTED("build-editor.new-level-started"),
	BUILD_EDITOR_SETUP_CANCELED("build-editor.setup-canceled"),
	BUILD_EDITOR_INVALID_INPUT("build-editor.invalid-input"),
	BUILD_EDITOR_LEVEL_CONFIG_SAVE_FAILED("build-editor.level-config-save-failed"),
	BUILD_EDITOR_SETUP_COMPLETE("build-editor.setup-complete"),
	BUILD_EDITOR_LEVEL_UPDATED("build-editor.level-updated"),
	BUILD_EDITOR_SETUP_STARTED("build-editor.setup-started"),
	BUILD_EDITOR_PROMPT_ITEMS("build-editor.prompt-items"),
	BUILD_EDITOR_PROMPT_EXPERIENCE("build-editor.prompt-experience"),
	BUILD_EDITOR_PROMPT_ECONOMY("build-editor.prompt-economy"),
	BUILD_EDITOR_PROMPT_SIZE("build-editor.prompt-size"),
	BUILD_EDITOR_PROMPT_CANCEL("build-editor.prompt-cancel"),

	VILLAGE_BLOCK_NAME("items.village-block"),
	VILLAGE_BLOCK_LORE("items.village-block-lore"),
	VILLAGE_DESTROYER_NAME("items.destroyer"),
	VILLAGE_DESTROYER_LORE("items.destroyer-lore"),
	VILLAGE_HEARTH_BLOCK_NAME("items.hearth"),
	VILLAGE_HEARTH_BLOCK_LORE("items.hearth-lore"),
	VILLAGE_PART_HEARTH_BLOCK_NAME("items.part-of-hearth"),
	VILLAGE_PART_HEARTH_BLOCK_LORE("items.part-of-hearth-lore"),
	VILLAGE_DESTROYER_HEARTH_NAME("items.destroyer-hearth"),
	VILLAGE_DESTROYER_HEARTH_LORE("items.destroyer-hearth-lore");

    @Getter private final String path;

    Lang(String path) {
        this.path = path;
    }
}
