package pl.kiosel.villages.config;

import lombok.Getter;
import pl.kiosel.rosacore.message.MessageKey;

public enum Lang implements MessageKey {

	COMMAND_RELOAD("command.reload"),
	COMMAND_CONSOLE("command.no-console"),
	COMMAND_ENABLED("command.not-enabled"),
	COMMAND_NO_PERMISSION("command.no-permission"),
	COMMAND_INVALID("command.invalid-number"),
	COMMAND_VILLAGE_NOT_FOUND("command.village-not-found"),
	COMMAND_UNKNOWN("command.unknown"),
	COMMAND_USAGE_CHAT("command.usage.chat"),
	COMMAND_USAGE_INVITE("command.usage.invite"),
	COMMAND_USAGE_REQUEST("command.usage.request"),
	COMMAND_USAGE_BUILD_EDITOR("command.usage.build-editor"),
	COMMAND_ADMIN_GIVE_ITEM("command.admin.give-item"),
	COMMAND_ADMIN_UPGRADE("command.admin.upgrade"),
	COMMAND_ADMIN_CANT_UPGRADE("command.admin.cant-upgrade"),
	COMMAND_ADMIN_DELETE("command.admin.delete"),
	COMMAND_ADMIN_PROTECTION_ADD("command.admin.protection-add"),
	COMMAND_ADMIN_PROTECTION_REMOVE("command.admin.protection-remove"),
	COMMAND_ADMIN_VILLAGE_NOT_FOUND("command.admin.village-not-found"),
	COMMAND_ADMIN_DEBUG_INFO("command.admin.debug.info"),
	COMMAND_ADMIN_DEBUG_NOT_SET("command.admin.debug.not-set"),
	COMMAND_ADMIN_DEBUG_NONE("command.admin.debug.none"),
	COMMAND_ADMIN_DEBUG_DIRTY("command.admin.debug.dirty"),
	COMMAND_ADMIN_DEBUG_SAVED("command.admin.debug.saved"),
	COMMAND_ADMIN_INTEGRATION_UNAVAILABLE("command.admin.integration.unavailable"),
	COMMAND_ADMIN_INTEGRATION_INSTALLED("command.admin.integration.installed"),
	COMMAND_ADMIN_INTEGRATION_RESTORED("command.admin.integration.restored"),
	COMMAND_ADMIN_INTEGRATION_STATUS("command.admin.integration.status"),
	COMMAND_ADMIN_INTEGRATION_ERROR("command.admin.integration.error"),

	COMMAND_ADMIN_BANK_ADD("command.admin.bank-add"),
	COMMAND_ADMIN_BANK_REMOVE("command.admin.bank-remove"),

	COMMAND_ADMIN_LIVES_ADD("command.admin.lives-add"),
	COMMAND_ADMIN_LIVES_REMOVE("command.admin.lives-remove"),
	COMMAND_ADMIN_ALREADY_DYING("command.admin.already-dying"),
	COMMAND_ADMIN_UPGRADE_FAILED("command.admin.upgrade-failed"),
	COMMAND_ADMIN_USAGE_ROOT("command.admin.usage.root"),
	COMMAND_ADMIN_USAGE_DEBUG("command.admin.usage.debug"),
	COMMAND_ADMIN_USAGE_GIVE("command.admin.usage.give"),
	COMMAND_ADMIN_USAGE_MANAGE("command.admin.usage.manage"),
	COMMAND_ADMIN_USAGE_INTEGRATION("command.admin.usage.integration"),
	COMMAND_ADMIN_USAGE_ACTION("command.admin.usage.action"),
	COMMAND_ADMIN_USAGE_NUMBER("command.admin.usage.number"),
	COMMAND_ADMIN_USAGE_DURATION("command.admin.usage.duration"),

	ADDON_DISABLED("general.addon-disabled"),
	FULL_EQ("general.player.you-have-full-eq"),
	MONEY_REMOVE("general.player.money-remove"),
	MONEY_ADD("general.player.money-add"),
	NO_MONEY("general.player.money-no"),
	NO_XP("general.player.no-xp"),
	NO_ITEMS("general.player.no-items"),
	MISSING_ITEM("general.player.missing-item"),
    PLAYER_OFFLINE("general.player.offline"),
	PLAYER_ONLINE("general.player.online"),
	PLAYER_NOT_FOUND("general.player.not-found"),
    HAS_VILLAGE("general.player.has-village"),
	TAKE_XP("general.player.take-xp"),
	TAKE_ITEMS("general.player.take-items"),
	SEPARATOR("general.separator"),
	ON("general.nametag.on"),
	OFF("general.nametag.off"),

	TELEPORT("teleport.teleporting"),
	TELEPORTED("teleport.teleported"),
	TELEPORT_COOLDOWN("teleport.cooldown"),
	TELEPORT_TITLE("teleport.title"),
	TELEPORT_SUBTITLE("teleport.subtitle"),
	TELEPORT_MOVE("teleport.move"),
	TELEPORT_SET("teleport.set"),
	TELEPORT_SET_CANCEL("teleport.set-cancel"),
	TELEPORT_SET_HOVER("teleport.set-hover"),
	TELEPORT_SET_TITLE("teleport.set-title"),
	TELEPORT_SET_SUBTITLE("teleport.set-subtitle"),
	TELEPORT_SET_OUT_OF_VILLAGE("teleport.outside-region"),

	CREATED("village.created"),
	DISABLED_WORLD("village.disabled-world"),
	VILLAGE_NO_PERMISSION("village.no-permission"),
	VILLAGE_NEARBY("village.nearby"),
	VILLAGE_SPAWN("village.spawn-nearby"),
	VILLAGE_REMOVE("village.remove"),
	VILLAGE_REMOVE_MEMBER("village.remove-member"),
	VILLAGE_ROLE_CHANGED("village.role-changed"),
	VILLAGE_UPGRADE("village.upgrade"),
	VILLAGE_CHAT_FORMAT("village.chat-format"),
	VILLAGE_NO_REQ_UPGRADE("village.upgrade-no-requirements"),
	VILLAGE_MAX_LEVEL("village.max-level"),
	VILLAGE_PROTECTED("village.protected"),
	VILLAGE_PROTECTED_OFFLINE("village.protected-offline-members"),
	VILLAGE_MUST_HAVE_TAG("village.have-tag"),
	VILLAGE_ATTACKED_TITLE("village.attacked.title"),
	VILLAGE_ATTACKED_SUBTITLE("village.attacked.subtitle"),
	VILLAGE_ATTACKED_MESSAGE("village.attacked.message"),
	VILLAGE_DESTROYED_TITLE("village.destroyed.title"),
	VILLAGE_DESTROYED_SUBTITLE("village.destroyed.subtitle"),
	VILLAGE_DESTROYED_MESSAGE("village.destroyed.message"),

	VILLAGE_HEARTH_ADD("village.hearth-add"),
	VILLAGE_MAX_LIVES("village.hearth-max-lives"),

	VILLAGE_IN("village.in-village"),
    VILLAGE_NO("village.no-village"),
    LEAVE_OWNER("village.leave-owner"),
	LEAVE_VILLAGE("village.leave-village"),
	LEAVE_VILLAGE_BROADCAST("village.leave-village-broadcast"),
	LEAVE_CONFIRM_VILLAGE("village.confirm-leave-village"),
	CANT_EDIT("village.cant-edit"),
	EFFECT_NOT_BUY("village.effect-not-bought"),

	BANK_ADD("village.bank-add"),
	BANK_REMOVE("village.bank-remove"),
	BANK_NO_MONEY("village.bank-no-money"),

	ENTER_VILLAGE_AREA_TITLE("village.enter-area-title"),
	ENTER_VILLAGE_AREA_SUBTITLE("village.enter-area-subtitle"),
	LEAVE_VILLAGE_AREA_TITLE("village.leave-area-title"),
	LEAVE_VILLAGE_AREA_SUBTITLE("village.leave-area-subtitle"),

	TAG_VILLAGE("tag.your-village-tag"),
	TAG_NEW_VILLAGE("tag.new-village-tag"),
	TAG_NO_SET_VILLAGE("tag.closed-name-village-tag"),
	TAG_ALREADY_SET_VILLAGE("tag.already-name-village-tag"),
	TAG_TRY_AGAIN("tag.try-again"),
	TAG_EMPTY("tag.empty"),
	TAG_SPACES("tag.has-spaces"),
	TAG_TOO_LONG("tag.too-long"),
	TAG_INVALID_CHARS("tag.invalid-chars"),
	TAG_NO("tag.no-tag"),

    HAS_INVITE("invite.has-invite"),
	NO_INVITE("invite.no-invite"),
	MAX_MEMBERS("invite.max-members"),
    PLAYER_INVITE("invite.player-invite"),
    PLAYER_TARGET("invite.player-target"),
	INVITE_CONFIRM("invite.confirm"),
	INVITE_CANCEL("invite.cancel"),
	INVITE_CONFIRM_HOVER("invite.confirm-hover-click"),
	INVITE_CANCEL_HOVER("invite.cancel-hover-click"),
	INVITE_CONFIRMED("invite.confirmed"),
	INVITE_DECLINE("invite.target-decline-member"),
	INVITE_CANCELED("invite.canceled"),
	TARGET_JOIN_MEMBER("invite.target-join-member"),

	SPAWN_SET("spawn.spawn-set"),
	SPAWN_NOT_SET("spawn.spawn-not-set"),
	SPAWN_TELEPORT("spawn.teleporting"),

	ANTILOGOUT_BLOCKED_REGION("antilogout.blocked-region"),
	ANTILOGOUT_BLOCK_COMMAND("antilogout.block-command"),
	ANTILOGOUT_STARTED("antilogout.started"),
	ANTILOGOUT_ATTACKED("antilogout.attacked"),
	ANTILOGOUT_END_COMBAT("antilogout.end-combat"),
	ANTILOGOUT_REMOVE_COMBAT("antilogout.remove-combat"),
	ANTILOGOUT_ACTIONBAR_MESSAGE("antilogout.actionbar-message"),
	ANTILOGOUT_QUIT_BROADCAST("antilogout.quit-broadcast"),

	QUESTS_COMMAND_DESCRIPTION("quests.command-description"),
	QUESTS_COMPLETED("quests.completed"),
	QUESTS_ACTIVATED("quests.activated"),

	RANKING_KILL("ranking.kill"),
	RANKING_DEATH("ranking.death"),
	RANKING_ASSIST("ranking.assist"),

	DIPLOMACY_UNAVAILABLE("diplomacy.unavailable"),
	DIPLOMACY_SAME_VILLAGE("diplomacy.same-village"),
	DIPLOMACY_ALLIANCE_COMMAND_DESCRIPTION("diplomacy.alliance.command-description"),
	DIPLOMACY_ALLIANCE_USAGE("diplomacy.alliance.usage"),
	DIPLOMACY_ALLIANCE_REQUEST_SENT("diplomacy.alliance.request-sent"),
	DIPLOMACY_ALLIANCE_REQUEST_RECEIVED("diplomacy.alliance.request-received"),
	DIPLOMACY_ALLIANCE_REQUEST_DENIED("diplomacy.alliance.request-denied"),
	DIPLOMACY_ALLIANCE_REQUEST_DENIED_SELF("diplomacy.alliance.request-denied-self"),
	DIPLOMACY_ALLIANCE_REQUEST_EXISTS("diplomacy.alliance.request-exists"),
	DIPLOMACY_ALLIANCE_NO_REQUEST("diplomacy.alliance.no-request"),
	DIPLOMACY_ALLIANCE_CREATED("diplomacy.alliance.created"),
	DIPLOMACY_ALLIANCE_ENDED("diplomacy.alliance.ended"),
	DIPLOMACY_ALLIANCE_ALREADY("diplomacy.alliance.already"),
	DIPLOMACY_ALLIANCE_NOT_ALLIED("diplomacy.alliance.not-allied"),
	DIPLOMACY_ALLIANCE_LIMIT("diplomacy.alliance.limit"),
	DIPLOMACY_ALLIANCE_WAR_CONFLICT("diplomacy.alliance.war-conflict"),
	DIPLOMACY_ALLIANCE_FRIENDLY_FIRE("diplomacy.alliance.friendly-fire"),
	DIPLOMACY_ALLIANCE_CANNOT_ATTACK("diplomacy.alliance.cannot-attack"),
	DIPLOMACY_ALLIANCE_LIST_HEADER("diplomacy.alliance.list.header"),
	DIPLOMACY_ALLIANCE_LIST_EMPTY("diplomacy.alliance.list.empty"),
	DIPLOMACY_ALLIANCE_LIST_ENTRY("diplomacy.alliance.list.entry"),
	DIPLOMACY_ALLIANCE_PENDING_HEADER("diplomacy.alliance.list.pending-header"),
	DIPLOMACY_WAR_COMMAND_DESCRIPTION("diplomacy.war.command-description"),
	DIPLOMACY_WAR_USAGE("diplomacy.war.usage"),
	DIPLOMACY_WAR_DECLARED_ATTACKER("diplomacy.war.declared-attacker"),
	DIPLOMACY_WAR_DECLARED_DEFENDER("diplomacy.war.declared-defender"),
	DIPLOMACY_WAR_STARTED("diplomacy.war.started"),
	DIPLOMACY_WAR_FINISHED("diplomacy.war.finished"),
	DIPLOMACY_WAR_DRAW("diplomacy.war.draw"),
	DIPLOMACY_WAR_ATTACKER_NO_VILLAGE("diplomacy.war.attacker-no-village"),
	DIPLOMACY_WAR_PREPARING("diplomacy.war.preparing"),
	DIPLOMACY_WAR_REQUIRED("diplomacy.war.required"),
	DIPLOMACY_WAR_ALLIED("diplomacy.war.allied"),
	DIPLOMACY_WAR_EXISTS("diplomacy.war.exists"),
	DIPLOMACY_WAR_COOLDOWN("diplomacy.war.cooldown"),
	DIPLOMACY_WAR_LIMIT("diplomacy.war.limit"),
	DIPLOMACY_WAR_NOT_ENOUGH_MEMBERS("diplomacy.war.not-enough-members"),
	DIPLOMACY_WAR_NOT_ENOUGH_ONLINE("diplomacy.war.not-enough-online"),
	DIPLOMACY_WAR_NOT_ENOUGH_BANK("diplomacy.war.not-enough-bank"),
	DIPLOMACY_WAR_NONE("diplomacy.war.none"),
	DIPLOMACY_WAR_LIST_HEADER("diplomacy.war.list.header"),
	DIPLOMACY_WAR_LIST_EMPTY("diplomacy.war.list.empty"),
	DIPLOMACY_WAR_LIST_ENTRY("diplomacy.war.list.entry"),
	DIPLOMACY_WAR_STATE_PREPARING("diplomacy.war.state.preparing"),
	DIPLOMACY_WAR_STATE_ACTIVE("diplomacy.war.state.active"),
	DIPLOMACY_WAR_STATE_FINISHED("diplomacy.war.state.finished"),
	DEVELOPMENT_UNLOCKED_BROADCAST("development.unlocked-broadcast"),
	DEVELOPMENT_ALREADY_UNLOCKED("development.already-unlocked"),
	DEVELOPMENT_LEVEL_REQUIRED("development.level-required"),
	DEVELOPMENT_PREREQUISITE_REQUIRED("development.prerequisite-required"),
	DEVELOPMENT_NOT_ENOUGH_BANK("development.not-enough-bank"),
	UPKEEP_PAID("village.upkeep-paid"),
	UPKEEP_MISSED("village.upkeep-missed"),
	UPKEEP_PENALTY("village.upkeep-penalty"),

	BUILD_EDITOR_WORLD_EDIT_REQUIRED("build-editor.worldedit-required"),
	BUILD_EDITOR_SETTING_REQUIRED("build-editor.setting-required"),
	BUILD_EDITOR_SESSION_ACTIVE("build-editor.session-active"),
	BUILD_EDITOR_LEVEL_MISSING("build-editor.level-missing"),
	BUILD_EDITOR_SCHEMATIC_MISSING("build-editor.schematic-missing"),
	BUILD_EDITOR_SCHEMATIC_TOO_LARGE("build-editor.schematic-too-large"),
	BUILD_EDITOR_SAFE_LOCATION_NOT_FOUND("build-editor.safe-location-not-found"),
	BUILD_EDITOR_STARTED("build-editor.started"),
	BUILD_EDITOR_BOUNDS_HELP("build-editor.bounds-help"),
	BUILD_EDITOR_COMMANDS_HELP("build-editor.commands-help"),
	BUILD_EDITOR_LOAD_FAILED("build-editor.load-failed"),
	BUILD_EDITOR_NO_SESSION("build-editor.no-session"),
	BUILD_EDITOR_SAVED("build-editor.saved"),
	BUILD_EDITOR_SAVED_HELP("build-editor.saved-help"),
	BUILD_EDITOR_SAVE_FAILED("build-editor.save-failed"),
	BUILD_EDITOR_CANCELED("build-editor.canceled"),
	BUILD_EDITOR_CORE_PROTECTED("build-editor.core-protected"),
	BUILD_EDITOR_OUTSIDE_BOUNDS("build-editor.outside-bounds"),
	BUILD_EDITOR_AREA_IN_USE("build-editor.area-in-use"),
	BUILD_EDITOR_SETUP_ACTIVE("build-editor.setup-active"),
	BUILD_EDITOR_MAX_LEVEL("build-editor.max-level"),
	BUILD_EDITOR_SETUP_RESUMED("build-editor.setup-resumed"),
	BUILD_EDITOR_NEW_LEVEL_STARTED("build-editor.new-level-started"),
	BUILD_EDITOR_SETUP_CANCELED("build-editor.setup-canceled"),
	BUILD_EDITOR_INVALID_INPUT("build-editor.invalid-input"),
	BUILD_EDITOR_LEVEL_CONFIG_SAVE_FAILED("build-editor.level-config-save-failed"),
	BUILD_EDITOR_SETUP_COMPLETE("build-editor.setup-complete"),
	BUILD_EDITOR_LEVEL_UPDATED("build-editor.level-updated"),
	BUILD_EDITOR_SETUP_STARTED("build-editor.setup-started"),
	BUILD_EDITOR_PROMPT_ITEMS("build-editor.prompt-items"),
	BUILD_EDITOR_PROMPT_EXPERIENCE("build-editor.prompt-experience"),
	BUILD_EDITOR_PROMPT_ECONOMY("build-editor.prompt-economy"),
	BUILD_EDITOR_PROMPT_SIZE("build-editor.prompt-size"),
	BUILD_EDITOR_PROMPT_CANCEL("build-editor.prompt-cancel"),

	VILLAGE_BLOCK_NAME("items.village-block"),
	VILLAGE_BLOCK_LORE("items.village-block-lore"),
	VILLAGE_DESTROYER_NAME("items.destroyer"),
	VILLAGE_DESTROYER_LORE("items.destroyer-lore"),
	VILLAGE_HEARTH_BLOCK_NAME("items.hearth"),
	VILLAGE_HEARTH_BLOCK_LORE("items.hearth-lore"),
	VILLAGE_PART_HEARTH_BLOCK_NAME("items.part-of-hearth"),
	VILLAGE_PART_HEARTH_BLOCK_LORE("items.part-of-hearth-lore"),
	VILLAGE_DESTROYER_HEARTH_NAME("items.destroyer-hearth"),
	VILLAGE_DESTROYER_HEARTH_LORE("items.destroyer-hearth-lore");

    @Getter private final String path;

    Lang(String path) {
        this.path = path;
    }
}
