name: '${project.name}'
version: '${project.version}'
main: pl.kiosel.villages.AdvancedVillages
description: '${project.description}'
author: Kiosel
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - Vault
  - Essentials
  - PlayerPoints
  - AdvancedPlayerList
