main: pl.kiosel.villages.AdvancedVillages
version: '${project.version}'
name: AdvancedVillages
authors: [ Kiosel ]
api-version: 1.13
description: Rewrite for plugin Wioski
website: kiosel.pl

softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - Vault
  - Reserve
  - PlayerPoints
